# OpenAI配置
openai:
  api_key: "your-api-key-here"  # 请替换为您的OpenAI API密钥
  model: "gpt-3.5-turbo"  # 使用的模型

# PPT配置
ppt:
  fonts:
    title: "Microsoft YaHei"
    subtitle: "Microsoft YaHei"
    content: "Microsoft YaHei"
  sizes:
    title: 44
    subtitle: 32
    content: 24
  page_size:
    width: 10  # 英寸
    height: 7.5  # 英寸
  margins:
    left: 1
    right: 1
    top: 1
    bottom: 1

# HTML配置
html:
  theme: "light"
  font_family: "Microsoft YaHei, sans-serif"
  colors:
    primary: "#1a73e8"  # Google Blue
    secondary: "#5f6368"  # Google Gray
    background: "#ffffff"
    text: "#202124"
    border: "#dadce0"
  code_theme: "github"

# 输出配置
output:
  path: "src/output"
  format: "pptx"
  quality: "high"

# 日志配置
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "src/output/conversion.log"

# 文档处理配置
document:
  supported_formats:
    - "docx"
    - "pdf"
    - "txt"
  max_file_size: 10485760  # 10MB
  encoding: "utf-8"

# 图表配置
chart:
  # 基础配置
  theme: "light"  # 图表主题
  animation: true  # 是否启用动画
  responsive: true  # 是否响应式
  height: 400  # 图表高度（像素）
  width: "100%"  # 图表宽度
  
  # 图表类型配置
  types:
    trend: "line"  # 趋势数据使用折线图
    proportion: "pie"  # 占比数据使用饼图
    comparison: "bar"  # 对比数据使用柱状图
    relationship: "graph"  # 关系数据使用关系图
    process: "flow"  # 流程数据使用流程图
  
  # 图表样式
  style:
    font: "Microsoft YaHei"  # 字体
    colors:  # 配色方案
      - [26, 115, 232]  # Google Blue
      - [52, 168, 83]   # Google Green
      - [251, 188, 4]   # Google Yellow
      - [234, 67, 53]   # Google Red
      - [103, 58, 183]  # Google Purple

# 分析设置
analysis:
  keywords:
    min_length: 2
    max_length: 10
    min_frequency: 2
  data_points:
    number_pattern: r'\d+(?:\.\d+)?'
    percentage_pattern: r'\d+(?:\.\d+)?%'
  timeline:
    date_pattern: r'\d{4}年|\d{4}-\d{2}-\d{2}'

# 可视化元素配置
visual:
  # 图标配置
  icons:
    size:
      title: 20  # 标题图标尺寸（px）
      content: 16  # 内容图标尺寸（px）
    color: "#1a73e8"  # 图标颜色
    spacing:
      title: 8  # 标题图标间距（px）
      content: 4  # 内容图标间距（px）
  
  # 分割线配置
  divider:
    animation:
      duration: 3  # 动画时长（秒）
      timing: "ease"  # 缓动函数
      infinite: true  # 无限循环
    gradient: true  # 使用渐变效果 